service: taskhero-api
app: taskhero-api
org: jacquesblom

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'
plugins:
    - serverless-plugin-typescript

provider:
    name: aws
    runtime: nodejs12.x

    environment:
        DYNAMODB_TABLE_TASKS: ${self:service}-tasks-${self:provider.stage}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:PutItem
              - dynamodb:Query
          Resource:
              - 'Fn::GetAtt': [DynamoDBTasks, Arn]
              - 'Fn::Join': ['/', ['Fn::GetAtt': [DynamoDBTasks, Arn], 'index', 'UserIdIndex']]

functions:
    get-tasks:
        handler: handlers/get-tasks.handler
        events:
            - http:
                  path: tasks
                  method: get
        environment:
            DYNAMODB_TABLE_TASKS: ${self:provider.environment.DYNAMODB_TABLE_TASKS}
    insert-task:
        handler: handlers/insert-task.handler
        events:
            - http:
                  path: tasks
                  method: post
        environment:
            DYNAMODB_TABLE_TASKS: ${self:provider.environment.DYNAMODB_TABLE_TASKS}
    update-task:
        handler: handlers/update-task.handler
        events:
            - http:
                  path: task/{id}
                  method: post
                  request:
                      parameters:
                          paths:
                              id: true
        environment:
            DYNAMODB_TABLE_TASKS: ${self:provider.environment.DYNAMODB_TABLE_TASKS}

resources:
    Resources:
        DynamoDBTasks:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: userId
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                GlobalSecondaryIndexes:
                    - IndexName: UserIdIndex
                      KeySchema:
                          - AttributeName: userId
                            KeyType: HASH
                      Projection:
                          ProjectionType: 'ALL'
                      ProvisionedThroughput:
                          ReadCapacityUnits: 1
                          WriteCapacityUnits: 1
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.DYNAMODB_TABLE_TASKS}
